### ISSUE TITLE
LocalPath object has no attribute endswith

### ISSUE THREAD

**Issue by mafalb** [tox-dev/tox-pipenv#8]
With the following tox.ini on a centos 7 machine I get an error when tox-pipenv is installed

```
[tox]
minversion = 1.8
envlist = py{27}-ansible{23,24}
skipsdist = true

[testenv]
passenv = *
deps =
    molecule==2.8
    ansible23: ansible==2.3
    ansible24: ansible==2.4
commands =
    molecule test
```

```
$ tox
py27-ansible23 create: /home/user1/ansible-module/.tox/py27-ansible23
Traceback (most recent call last):
  File "/home/user1/.local/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "/home/user1/.local/lib/python2.7/site-packages/tox/session.py", line 40, in main
    retcode = Session(config).runcommand()
  File "/home/user1/.local/lib/python2.7/site-packages/tox/session.py", line 392, in runcommand
    return self.subcommand_test()
  File "/home/user1/.local/lib/python2.7/site-packages/tox/session.py", line 558, in subcommand_test
    if self.setupenv(venv):
  File "/home/user1/.local/lib/python2.7/site-packages/tox/session.py", line 457, in setupenv
    status = venv.update(action=action)
  File "/home/user1/.local/lib/python2.7/site-packages/tox/venv.py", line 169, in update
    self.hook.tox_testenv_create(action=action, venv=self)
  File "/home/user1/.local/lib/python2.7/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/user1/.local/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/user1/.local/lib/python2.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/home/user1/.local/lib/python2.7/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "/home/user1/.local/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
    _reraise(*ex)  # noqa
  File "/home/user1/.local/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/home/user1/.local/lib/python2.7/site-packages/tox_pipenv/plugin.py", line 22, in tox_testenv_create
    pipfile_path = os.path.join(venv.path, 'Pipfile')
  File "/usr/lib64/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'LocalPath' object has no attribute 'endswith'
```

pipenv, tox and tox-pipenv were installed by user

```
$ pip freeze --user
backports.shutil-get-terminal-size==1.0.0
certifi==2018.1.18
configparser==3.5.0
enum34==1.1.6
flake8==3.5.0
idna==2.6
mccabe==0.6.1
pathlib==1.0.1
pew==1.1.2
pipenv==9.0.1
pluggy==0.6.0
py==1.5.2
pycodestyle==2.3.1
pyflakes==1.6.0
shutilwhich==1.1.0
tox==2.9.1
tox-pipenv==1.2.1
virtualenv==15.1.0
virtualenv-clone==0.2.6
```

**Comment by thedrow** [comment]
Seems like `venv.path` is a `pathlib.Path` and not a string in some cases.
There is an easy fix though. I'll try to find time to work on a PR.

**Comment by thedrow** [comment]
Can you check my PR and see if that works for you?

**Comment by tonybaloney** [comment]
released in 1.3.0

**Comment by thedrow** [comment]
@tonybaloney Why did you reopen?

**Comment by tonybaloney** [comment]
@thedrow I don’t normally close an issue unless the raiser confirms it has been fixed

**Comment by jakul** [comment]
This is still happening for me with 1.3, but now on a different line. You need to apply the same fix everywhere you have `os.path.join(venv.path)` @tonybaloney

**Comment by thedrow** [comment]
Already did in #12 :)
